name: simplenoteapp
description: "Simple Flutter app for making notes"
publish_to: "none"

version: 0.1.1+beta

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.2
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
