name: "Build a Simple Note App binaries for Windows"

on:
  workflow_run:
    workflows: ["Create a release"]
    types:
      - completed

jobs:
  build-windows:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone Flutter repository with main channel
        id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check the Flutter environment
        id: flutter-check
        run: flutter doctor

      - name: Get dependencies
        id: get-flutter-dependencies
        run: flutter pub get

      - name: Build Windows binaries
        id: build-windows-binaries
        run: flutter build windows --release

      - name: Copy sqlite3 package for windows
        id: copy-sqlite3
        run: cp -r windows/sqlite3.dll build/windows/x64/runner/Release/

      - name: Pack the binaries
        id: pack-binaries
        run: 7z a -tzip simplenoteapp-windows.zip build\windows\x64\runner\Release\*

      - name: Upload a Windows artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: simplenoteapp-windows.zip
          tag: v0.1.1-beta
          release_name: v0.1.1-beta
          overwrite: true
