name: "Build a Simple Note App"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action
        with:
          flutter-version: latest
      - run: flutter doctor
