name: "Build a Simple Note App binaries for Windows"

on:
  workflow_run:
    workflows: ["Simple Note App tests"]
    types:
      - completed

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone Flutter repository with main channel
        id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check the Flutter environment
        id: flutter-check
        run: flutter doctor

      - name: Get dependencies
        id: get-flutter-dependencies
        run: flutter pub get
        working-directory: ../..

      - name: Build Windows binaries
        id: build-windows-binaries
        run: flutter build windows --release
        working-directory: ../..

      - name: Upload Windows binaries
        id: upload-windows-binaries
        uses: actions/upload-artifact@v2
        with:
          name: simplenoteapp-windows
          path: build/windows/runner/Release
