name: "Build a Simple Note App binaries for Linux"

on:
  workflow_run:
    workflows: ["Create a release"]
    types:
      - completed

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Clone Flutter repository with main channel
        id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux dependencies
        id: install-apt-dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build libgtk-3-dev

      - name: Checks the Flutter environment
        id: flutter-check
        run: flutter doctor

      - name: Install dependencies
        id: get-flutter-dependencies
        run: flutter pub get

      - name: Build Linux binaries
        id: linux-build-binaries
        run: flutter build linux --release

      - name: Pack binaries
        id: pack-binaries
        run: tar -czf simplenoteapp-linux.tar.gz build/linux/release

      - name: Upload a Windows artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: simplenoteapp-linux.tar.gz
          tag: v0.1.1-beta
          release_name: v0.1.1-beta
          overwrite: true
