name: "Build a Simple Note App"

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone Flutter repository with main channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: "Cache Flutter dependencies"
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build libgtk-3-dev

      - name: Cache Linux dependencies
        id: cache-apt
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt.lock') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Checks the flutter environment
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux --release

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v2
        # if: github.event_name != 'pull_request' && github.repository == 'simplenoteapp'
        with:
          name: linux-binary
          path: build/linux/x64/release/bundle/
