name: "Create a release"

on:
  workflow_run:
    workflows: ["Simple Note App tests"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.1-beta
          release_name: v0.1.1-beta
          body: |
            This is a first release of my new app. It's still in beta, but it's already working.
            At now you can create, read, update and delete notes.
            Also you can change the app theme and reset all notes.
            I'll be happy to hear your feedback.
          draft: false
          prerelease: true
